### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by Taza53** [jlam55555/veikk-linux-driver-gui#11]

**Comment by jlam55555** [comment]
This GitHub repo doesn't really "install" anything anywhere -- it simply builds the program in the current directory. To uninstall it, simply remove the repo directory.

It's a different story if you installed it through a package manager, such as the AUR -- if that's the case, then uninstall it using that package manager.

To really uninstall everything, you may also have to remove the config file in /etc/modprobe.d/ and any config files you manually saved anywhere else.
