### ISSUE TITLE
Unkown Module core gui widgets

### ISSUE THREAD

**Issue by deekumar24** [jlam55555/veikk-linux-driver-gui#3]
When I tried to run qmake, I got this error. 

**Project ERROR: Unknown module(s) in QT: core gui widgets**

So I check the version and got this -

**QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu**

**Comment by sudheerbussa** [comment]
same error here on Parrot Mate

**Comment by ExpertSunny** [comment]
I've managed to install the GUI on Parrot OS. This error can be avoided by installing the following packages.
qt5-default, qt5-qmake, qt5-qmake-bin

Run the following commands:
sudo apt-get update
sudo apt-get install qt5-default qt5-qmake qt5-qmake-bin

**Comment by jlam55555** [comment]
Closing because not related to this tool -- related to Qt installation.
